export const USER_EDIT = 'USER_EDIT';
export const USER_SAVE = 'USER_SAVE';
export const USER_DECREASE_NOTIFICATION = 'USER_DECREASE_NOTIFICATION';

export const SAVE_NEW_FLAGS = 'SAVE_NEW_FLAGS';

export const SAVE_MY_CAMPAIGN_DATA = 'SAVE_MY_CAMPAIGN_DATA';
export const SAVE_SHARE_CAMPAIGN_DATA = 'SAVE_SHARE_CAMPAIGN_DATA';
