export const SCHEDULE_ADD = 'SCHEDULE_ADD';
export const SCHEDULE_REMOVE = 'SCHEDULE_REMOVE';
export const SCHEDULE_FETCH = 'SCHEDULE_FETCH';

export const APPLY_FILTER = 'APPLY_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const ALLOW_NOTIFICATION = 'ALLOW_NOTIFICATION';

export const PUSH_KEY = 'PUSH_MODAL_OPENED';
export const PUSH_STATUS_KEY = 'PUSH_STATUS_KEY';
